// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Q4LC5NaxA6kKMcWzwA4_xgKi8ZAVxLY',
    appId: '1:213763883943:web:5ec1e5c8b1a9ca70afac82',
    messagingSenderId: '213763883943',
    projectId: 'chat-app-acec9',
    authDomain: 'chat-app-acec9.firebaseapp.com',
    storageBucket: 'chat-app-acec9.appspot.com',
    measurementId: 'G-VTNQZ3N5JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6iKGHBm5v2WmLvQEOfU-POB5GMMv5l4',
    appId: '1:213763883943:android:55b358e0405a3f3eafac82',
    messagingSenderId: '213763883943',
    projectId: 'chat-app-acec9',
    storageBucket: 'chat-app-acec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZbhmVS1o-JXxk-IjGS57TWjkaIPi73WY',
    appId: '1:213763883943:ios:353b57623b2fbaebafac82',
    messagingSenderId: '213763883943',
    projectId: 'chat-app-acec9',
    storageBucket: 'chat-app-acec9.appspot.com',
    iosClientId: '213763883943-je5mrl7grjokgsdhlf3t4qsqg8pd4nh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZbhmVS1o-JXxk-IjGS57TWjkaIPi73WY',
    appId: '1:213763883943:ios:353b57623b2fbaebafac82',
    messagingSenderId: '213763883943',
    projectId: 'chat-app-acec9',
    storageBucket: 'chat-app-acec9.appspot.com',
    iosClientId: '213763883943-je5mrl7grjokgsdhlf3t4qsqg8pd4nh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
